name: Automatic Testing and Deployment
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install --platform=linux --arch=x64 sharp
      
      - run: bun run benchmark
      - run: bun run test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}